[package]
name = "chain-time"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
chain-ser = { path = "../chain-ser" }
chain-core = { path = "../chain-core" }

quickcheck = { version = "0.9", optional = true }
proptest = { git = "https://github.com/input-output-hk/proptest.git", optional = true }
test-strategy = { version = "0.1", optional = true }
serde = { version = "1.0", features = ["derive"] }

[features]
property-test-api = ["quickcheck", "proptest", "test-strategy"]

[dev-dependencies]
quickcheck = "0.9"
proptest = { git = "https://github.com/input-output-hk/proptest.git" }
test-strategy = "0.1"
