[package]
name = "sparse-array"
version = "0.1.0"
authors = ["Yevhenii Babichenko <eugene.babichenko@iohk.io>"]
edition = "2021"

[dev-dependencies]
proptest = { git = "https://github.com/input-output-hk/proptest.git" }
test-strategy = "0.1"
