[package]
name = "chain-vote"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>"]
edition = "2018"

[dependencies]
rand_core = "0.6"
rayon = "1.5"
thiserror = "1.0"
cryptoxide = "0.3"
# TODO replace with the crates.io version once it has faster scalar multiplication
eccoxide = { git = "https://github.com/eugene-babichenko/eccoxide.git", branch = "fast-u64-scalar-mul", features = ["fast-u64-scalar-mul"], optional = true }
zerocaf = { version = "0.2", optional = true }

[dev-dependencies]
rand_chacha = "0.3"
smoke = "^0.2.1"
criterion = { version = "0.3" }

[features]
default = ["p256k1"]
p256k1 = ["eccoxide"]
ed = ["zerocaf"]

[[bench]]
harness = false
name = "shvzk"

[[bench]]
harness = false
name = "curve"
