[package]
name = "network-grpc"
version = "0.1.0"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
chain-core = { path = "../chain-core" }
network-core = { path = "../network-core" }
bytes = "0.5"
futures = "0.1"
http = "0.1.16"
http-connection = "0.1"
hyper = "0.12"
prost = "0.5"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-uds = "0.2"
tokio-executor = "0.1"
tower-hyper = "0.1.1"
tower-grpc = "0.1.1"
tower-request-modifier = "0.1"
tower-service = "0.2"
tower-util = "0.1"

[build-dependencies]
tower-grpc-build = { version = "0.1", features = ["tower-hyper"] }
