on:
  push:
    branches:
      - master
  pull_request:

name: Continuous integration

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - name: Fetch commit hash of the crates.io registry index
        shell: bash
        run: |
          commit=$(git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master | cut -f1)
          echo "$commit"
          echo "::set-env name=CRATES_IO_SHA::$commit"

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-v1-${{ hashFiles('**/Cargo.toml') }}-${{ env.CRATES_IO_SHA }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-v1-${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-cargo-registry-v1-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: fmt
          args: --all -- --check

      - name: Check build
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: check

      - name: Run test suite
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test

      - name: Check clippy lints
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: clippy
          # args: -- -D warnings # TODO: uncomment when ready to enforce all warning lints
